source /software/hgi/installs/anaconda3/etc/profile.d/conda.sh
conda activate /lustre/scratch125/humgen/projects/ddd/users/kc18/envs/recwest

i=${LSB_JOBINDEX}

chrom=`sed -n "$i{p;q}" /nfs/users/nfs_k/kc18/ddd/recwest/scripts/burden_test/interval_list.txt |  awk '{print $1}'`
g1=`sed -n "$i{p;q}" /nfs/users/nfs_k/kc18/ddd/recwest/scripts/burden_test/interval_list.txt |  awk '{print $2}'`
g2=`sed -n "$i{p;q}" /nfs/users/nfs_k/kc18/ddd/recwest/scripts/burden_test/interval_list.txt |  awk '{print $3}'`

python /nfs/users/nfs_k/kc18/ddd/recwest/scripts/burden_test/parse.py --vcf /nfs/users/nfs_k/kc18/vcfs_ddd/${chrom}.bcf --pop /nfs/users/nfs_k/kc18/ddd/recwest/data/new_pops_170921_atleast1parent_incladmixparents.txt --gen /nfs/users/nfs_k/kc18/resources/biomart/gene_pos_hg19_protein_coding_only_unique_EnsemblIDs_intersect_baits.txt --idmap /nfs/users/nfs_k/kc18/ddd/recwest/data/vcf_ids_cleaned.txt --ped /nfs/users/nfs_k/kc18/ddd/recwest/data/sanger_and_ega_ids.ped --cadd /nfs/users/nfs_k/kc18/resources/cadd_scores/cadd_scores_hg19_v1.6/whole_genome_SNVs.tsv.gz --mpc /nfs/users/nfs_k/kc18/resources/mpc_scores/hg19/fordist_constraint_official_mpc_values_v2.txt.gz --gmd /nfs/users/nfs_k/kc18/resources/gnomAD/version_2.1.1_b37/gnomad.exomes.r2.1.1.sites.${chrom}.vcf.bgz --revel /nfs/users/nfs_k/kc18/ddd/recwest/data/missense_pathogenicity_scores/revel_scores.txt.gz --chr ${chrom} --g1 ${g1} --g2 ${g2} --gmdversion gnomAD2.1 --unrelpar /nfs/users/nfs_k/kc18/ddd/ddd_samplelists/unrelated_parents_KINGgt0.04419417_fulltriosonly.txt --cadd-indels /nfs/users/nfs_k/kc18/resources/cadd_scores/cadd_scores_hg19_v1.6/InDels.tsv.gz --primateai /nfs/users/nfs_k/kc18/ddd/recwest/data/missense_pathogenicity_scores/PrimateAI_scores_v0.2_sorted.tsv.gz --varity /nfs/users/nfs_k/kc18/ddd/recwest/data/missense_pathogenicity_scores/varity/varity_all_predictions.txt.gz --spliceai /lustre/scratch125/humgen/resources/SpliceAI_data_files/spliceai_scores.masked.snv.hg19.vcf.gz --spliceai-indels /lustre/scratch125/humgen/resources/SpliceAI_data_files/spliceai_scores.masked.indel.hg19.vcf.gz --unaffectedpar /nfs/users/nfs_k/kc18/ddd/recwest/data/unaffected_parents.txt --outdir /nfs/users/nfs_k/kc18/ddd/recwest/results/burden_test/DDD_all/variants/redo/

#python /nfs/users/nfs_k/kc18/ddd/recwest/scripts/burden_test/variants_ddd.py --chrom $chrom --g1 $g1 --g2 $g2 --popfile /nfs/users/nfs_k/kc18/ddd/recwest/data/pops_splitAFR4_noadmixed_fulltrios.txt --pedfile /nfs/users/nfs_k/kc18/ddd/ddd_samplelists/sanger_and_ega_ids.ped --genepos /nfs/users/nfs_k/kc18/resources/biomart/gene_pos_hg19.txt --rohs_dir /nfs/users/nfs_k/kc18/ddd/recwest/results/rohs/ --input_dir /nfs/users/nfs_k/kc18/ddd/recwest/results/burden_test/DDD_all/ --idmap /nfs/users/nfs_k/kc18/ddd/recwest/data/vcf_ids.txt
