python parse.py --vcf 1.bcf 
--pop pops.txt 
--gen gene_pos_hg19_protein_coding_only_unique_EnsemblIDs_intersect_baits.txt 
--ped sanger_and_ega_ids.ped 
--cadd whole_genome_SNVs.tsv.gz 
--gmd gnomad.exomes.r2.1.1.sites.${chrom}.vcf.bgz 
--revel revel_scores.txt.gz 
--chr 1 --g1 1 --g2 10 --gmdversion gnomAD2.1 
--unrelpar unrelated_unaffected_parents_KINGgt0.04419417.txt 
--cadd-indels cadd_scores_hg19_v1.6/InDels.tsv.gz 
--varity varity_all_predictions.txt.gz 
--spliceai spliceai_scores.masked.snv.hg19.vcf.gz 
--spliceai-indels spliceai_scores.masked.indel.hg19.vcf.gz 
--outdir outdir
