python variants.py \
    --chrom 1 \
    --g1 1 \
    --g2 10 \
    --popfile test/population_table.txt \
    --pedfile test/pedigree.ped \
    --unrel_parents test/unrel_par.txt \
    --unrel_probands test/unrel_pro.txt \
    --genepos data/gene_pos.txt.gz \
    --rohs_dir test/ \
    --input_dir test/output/ \
    --output_dir test/output/
